# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e24f95f06f08f18a51efb714cd9ccbff51a028b4007f7b0f80546c503bcafc40047d2c085df3a1996a0053606fd17c7cb1bd7c0801a787155d279cfcefb1eba0

test:
  secret_key_base: baac960ee7841631a418116d5522a8102a28678da2088b53b866781e74450d8206dfec570396cb2e1ca60fdceaa054a491f294c0b5e71567c6935042b022ec58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
